---
- name: Converge
  hosts: instance01
  tasks:
    - name: Update repositories cache and install nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: yes
    - name: Make sure a nginx is running
      ansible.builtin.systemd:
        state: started
        name: nginx