---
image: python:3.10-slim

stages:
  - test
  - pre-release
  - release
  - migrate
  - deploy

include:
  - local: .gitlab-ci/test.yml
  - local: .gitlab-ci/release.yml
  - project: artem-shestakov/pipeline-template
    file: github_mirror.yml
    ref: master
  # - local: .gitlab-ci/deploy.yml
