deploy:
  stage: deploy
  image: artemshestakov/ansible:5.6.0
  variables:
    PY_COLORS: 1
  script:
    - ansible-galaxy role import --api-key $GALAXY_API_KEY $GITHUB_USER $CI_PROJECT_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      when: manual
    - if: '$CI_COMMIT_BRANCH != "master" || $CI_COMMIT_TAG'
      when: never
  tags:
    - docker.sock 