---
test:ansible-lint:
  stage: test
  before_script:
    - apt update && apt install -y git
    - pip install ansible==$ANSIBLE_VERSION ansible-lint yamllint
  script:
    - ansible-lint -v
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_PIPELINE_SOURCE == "push"'
      when: manual
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - docker.sock

test:yamllint:
  stage: test
  before_script:
    - apt update && apt install -y git
    - pip install ansible==$ANSIBLE_VERSION ansible-lint yamllint
  script:
    - yamllint .
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_PIPELINE_SOURCE == "push"'
      when: manual
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - docker.sock

test:molecule:
  stage: test
  image: artemshestakov/ansible:5.6.0
  variables:
    PY_COLORS: 1
  script:
    - molecule test -s master-master
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_PIPELINE_SOURCE == "push"'
      when: manual
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - docker.sock 
