---
- name: Enable and start Keepalived
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true

- name: Re-start Keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
