---
interface: eth0
vip:
  - 172.20.0.13
  - 172.20.0.14
global_defs:
  notification_email:
    - attem.s.shestakov@company.local
  notification_email_from: keepalive@mail.local
  smtp_server: 127.0.0.1
  smtp_connect_timeout: 60
vrrp_instance:
  authentication:
    auth_type: PASS
    auth_pass: $uper_$ecret
vrrp_script:
  name: nginx
  script: '/usr/bin/pgrep nginx'
  interval: 1